# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CGI\Scripts\TexConverter\widgets\toTex.ui'
#
# Created: Sat Oct 13 16:53:26 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_toTex(object):
    def setupUi(self, toTex):
        toTex.setObjectName("toTex")
        toTex.resize(900, 700)
        toTex.setMinimumSize(QtCore.QSize(900, 700))
        self.centralWidget = QtGui.QWidget(toTex)
        self.centralWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.centralWidget.setObjectName("centralWidget")
        self.layout_main = QtGui.QVBoxLayout(self.centralWidget)
        self.layout_main.setSpacing(0)
        self.layout_main.setContentsMargins(0, 0, 0, 0)
        self.layout_main.setObjectName("layout_main")
        self.layout_top = QtGui.QHBoxLayout()
        self.layout_top.setSpacing(0)
        self.layout_top.setContentsMargins(-1, 4, -1, -1)
        self.layout_top.setObjectName("layout_top")
        self.layout_main.addLayout(self.layout_top)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.layout_list_main = QtGui.QVBoxLayout()
        self.layout_list_main.setSpacing(0)
        self.layout_list_main.setContentsMargins(5, -1, -1, -1)
        self.layout_list_main.setObjectName("layout_list_main")
        self.horizontalLayout_7.addLayout(self.layout_list_main)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setContentsMargins(0, 10, 20, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(10000000, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setText("NEWER")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setMargin(0)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.button_switch = QtGui.QPushButton(self.centralWidget)
        self.button_switch.setMinimumSize(QtCore.QSize(32, 20))
        self.button_switch.setMaximumSize(QtCore.QSize(32, 20))
        self.button_switch.setText("")
        self.button_switch.setCheckable(True)
        self.button_switch.setFlat(True)
        self.button_switch.setObjectName("button_switch")
        self.horizontalLayout_13.addWidget(self.button_switch)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.label = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(6)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 170, 170);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label.setObjectName("label")
        self.verticalLayout_13.addWidget(self.label)
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setEnabled(True)
        self.line.setMinimumSize(QtCore.QSize(220, 0))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_13.addWidget(self.line)
        self.verticalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(-1, 40, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(20, 0, 20, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_resize = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_resize.sizePolicy().hasHeightForWidth())
        self.label_resize.setSizePolicy(sizePolicy)
        self.label_resize.setMinimumSize(QtCore.QSize(0, 0))
        self.label_resize.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.label_resize.setFont(font)
        self.label_resize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_resize.setText("RESIZE")
        self.label_resize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_resize.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_resize.setObjectName("label_resize")
        self.horizontalLayout_10.addWidget(self.label_resize)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.widget_resize = QtGui.QWidget(self.centralWidget)
        self.widget_resize.setStyleSheet("")
        self.widget_resize.setObjectName("widget_resize")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_resize)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.button_none = QtGui.QPushButton(self.widget_resize)
        self.button_none.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_none.setFont(font)
        self.button_none.setCheckable(True)
        self.button_none.setFlat(True)
        self.button_none.setObjectName("button_none")
        self.verticalLayout_12.addWidget(self.button_none)
        self.button_disabled = QtGui.QPushButton(self.widget_resize)
        self.button_disabled.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_disabled.setFont(font)
        self.button_disabled.setText("")
        self.button_disabled.setCheckable(True)
        self.button_disabled.setFlat(True)
        self.button_disabled.setObjectName("button_disabled")
        self.verticalLayout_12.addWidget(self.button_disabled)
        self.horizontalLayout_8.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.button_up = QtGui.QPushButton(self.widget_resize)
        self.button_up.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_up.setFont(font)
        self.button_up.setCheckable(True)
        self.button_up.setFlat(True)
        self.button_up.setObjectName("button_up")
        self.verticalLayout_11.addWidget(self.button_up)
        self.button_up_ = QtGui.QPushButton(self.widget_resize)
        self.button_up_.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_up_.setFont(font)
        self.button_up_.setCheckable(True)
        self.button_up_.setFlat(True)
        self.button_up_.setObjectName("button_up_")
        self.verticalLayout_11.addWidget(self.button_up_)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.button_down = QtGui.QPushButton(self.widget_resize)
        self.button_down.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_down.setFont(font)
        self.button_down.setCheckable(True)
        self.button_down.setFlat(True)
        self.button_down.setObjectName("button_down")
        self.verticalLayout_10.addWidget(self.button_down)
        self.button_down_ = QtGui.QPushButton(self.widget_resize)
        self.button_down_.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_down_.setFont(font)
        self.button_down_.setCheckable(True)
        self.button_down_.setFlat(True)
        self.button_down_.setObjectName("button_down_")
        self.verticalLayout_10.addWidget(self.button_down_)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.button_round = QtGui.QPushButton(self.widget_resize)
        self.button_round.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_round.setFont(font)
        self.button_round.setCheckable(True)
        self.button_round.setFlat(True)
        self.button_round.setObjectName("button_round")
        self.verticalLayout_9.addWidget(self.button_round)
        self.button_round_ = QtGui.QPushButton(self.widget_resize)
        self.button_round_.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_round_.setFont(font)
        self.button_round_.setCheckable(True)
        self.button_round_.setFlat(True)
        self.button_round_.setObjectName("button_round_")
        self.verticalLayout_9.addWidget(self.button_round_)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout.addWidget(self.widget_resize)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(20, 0, 20, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_wrap = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_wrap.sizePolicy().hasHeightForWidth())
        self.label_wrap.setSizePolicy(sizePolicy)
        self.label_wrap.setMinimumSize(QtCore.QSize(0, 0))
        self.label_wrap.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.label_wrap.setFont(font)
        self.label_wrap.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_wrap.setText("WRAP MODE")
        self.label_wrap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_wrap.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_wrap.setObjectName("label_wrap")
        self.horizontalLayout_11.addWidget(self.label_wrap)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.widget_wrap = QtGui.QWidget(self.centralWidget)
        self.widget_wrap.setStyleSheet("")
        self.widget_wrap.setObjectName("widget_wrap")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_wrap)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_black = QtGui.QPushButton(self.widget_wrap)
        self.button_black.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_black.setFont(font)
        self.button_black.setAutoFillBackground(False)
        self.button_black.setStyleSheet("")
        self.button_black.setCheckable(True)
        self.button_black.setFlat(True)
        self.button_black.setObjectName("button_black")
        self.horizontalLayout.addWidget(self.button_black)
        self.button_clamp = QtGui.QPushButton(self.widget_wrap)
        self.button_clamp.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_clamp.setFont(font)
        self.button_clamp.setCheckable(True)
        self.button_clamp.setFlat(True)
        self.button_clamp.setObjectName("button_clamp")
        self.horizontalLayout.addWidget(self.button_clamp)
        self.button_periodic = QtGui.QPushButton(self.widget_wrap)
        self.button_periodic.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_periodic.setFont(font)
        self.button_periodic.setCheckable(True)
        self.button_periodic.setFlat(True)
        self.button_periodic.setObjectName("button_periodic")
        self.horizontalLayout.addWidget(self.button_periodic)
        self.verticalLayout_2.addWidget(self.widget_wrap)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(20, 0, 20, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_mipmap = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mipmap.sizePolicy().hasHeightForWidth())
        self.label_mipmap.setSizePolicy(sizePolicy)
        self.label_mipmap.setMinimumSize(QtCore.QSize(0, 0))
        self.label_mipmap.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.label_mipmap.setFont(font)
        self.label_mipmap.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_mipmap.setText("MIPMAPING")
        self.label_mipmap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mipmap.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_mipmap.setObjectName("label_mipmap")
        self.horizontalLayout_14.addWidget(self.label_mipmap)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.widget_mipmap = QtGui.QWidget(self.centralWidget)
        self.widget_mipmap.setStyleSheet("")
        self.widget_mipmap.setObjectName("widget_mipmap")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_mipmap)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_single = QtGui.QPushButton(self.widget_mipmap)
        self.button_single.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_single.setFont(font)
        self.button_single.setCheckable(True)
        self.button_single.setFlat(True)
        self.button_single.setObjectName("button_single")
        self.horizontalLayout_4.addWidget(self.button_single)
        self.button_diagonal = QtGui.QPushButton(self.widget_mipmap)
        self.button_diagonal.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_diagonal.setFont(font)
        self.button_diagonal.setCheckable(True)
        self.button_diagonal.setFlat(True)
        self.button_diagonal.setObjectName("button_diagonal")
        self.horizontalLayout_4.addWidget(self.button_diagonal)
        self.button_all = QtGui.QPushButton(self.widget_mipmap)
        self.button_all.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_all.setFont(font)
        self.button_all.setCheckable(True)
        self.button_all.setFlat(True)
        self.button_all.setObjectName("button_all")
        self.horizontalLayout_4.addWidget(self.button_all)
        self.verticalLayout_4.addWidget(self.widget_mipmap)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(20, 0, 20, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_format = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_format.sizePolicy().hasHeightForWidth())
        self.label_format.setSizePolicy(sizePolicy)
        self.label_format.setMinimumSize(QtCore.QSize(0, 0))
        self.label_format.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.label_format.setFont(font)
        self.label_format.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_format.setText("FORMAT")
        self.label_format.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_format.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_format.setObjectName("label_format")
        self.horizontalLayout_15.addWidget(self.label_format)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.widget_format = QtGui.QWidget(self.centralWidget)
        self.widget_format.setStyleSheet("")
        self.widget_format.setObjectName("widget_format")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_format)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_tiff = QtGui.QPushButton(self.widget_format)
        self.button_tiff.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_tiff.setFont(font)
        self.button_tiff.setCheckable(True)
        self.button_tiff.setFlat(True)
        self.button_tiff.setObjectName("button_tiff")
        self.horizontalLayout_5.addWidget(self.button_tiff)
        self.button_pixar = QtGui.QPushButton(self.widget_format)
        self.button_pixar.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_pixar.setFont(font)
        self.button_pixar.setCheckable(True)
        self.button_pixar.setFlat(True)
        self.button_pixar.setObjectName("button_pixar")
        self.horizontalLayout_5.addWidget(self.button_pixar)
        self.button_openexr = QtGui.QPushButton(self.widget_format)
        self.button_openexr.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_openexr.setFont(font)
        self.button_openexr.setCheckable(True)
        self.button_openexr.setFlat(True)
        self.button_openexr.setObjectName("button_openexr")
        self.horizontalLayout_5.addWidget(self.button_openexr)
        self.verticalLayout_5.addWidget(self.widget_format)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(20, 0, 20, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_data = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_data.sizePolicy().hasHeightForWidth())
        self.label_data.setSizePolicy(sizePolicy)
        self.label_data.setMinimumSize(QtCore.QSize(0, 0))
        self.label_data.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        font.setWeight(75)
        font.setBold(True)
        self.label_data.setFont(font)
        self.label_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_data.setText("DATA TYPE")
        self.label_data.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_data.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_data.setObjectName("label_data")
        self.horizontalLayout_16.addWidget(self.label_data)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.widget_data = QtGui.QWidget(self.centralWidget)
        self.widget_data.setStyleSheet("")
        self.widget_data.setObjectName("widget_data")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_data)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_byte = QtGui.QPushButton(self.widget_data)
        self.button_byte.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_byte.setFont(font)
        self.button_byte.setCheckable(True)
        self.button_byte.setFlat(True)
        self.button_byte.setObjectName("button_byte")
        self.horizontalLayout_6.addWidget(self.button_byte)
        self.button_short = QtGui.QPushButton(self.widget_data)
        self.button_short.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_short.setFont(font)
        self.button_short.setCheckable(True)
        self.button_short.setFlat(True)
        self.button_short.setObjectName("button_short")
        self.horizontalLayout_6.addWidget(self.button_short)
        self.button_half = QtGui.QPushButton(self.widget_data)
        self.button_half.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_half.setFont(font)
        self.button_half.setCheckable(True)
        self.button_half.setFlat(True)
        self.button_half.setObjectName("button_half")
        self.horizontalLayout_6.addWidget(self.button_half)
        self.button_float = QtGui.QPushButton(self.widget_data)
        self.button_float.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_float.setFont(font)
        self.button_float.setCheckable(True)
        self.button_float.setFlat(True)
        self.button_float.setObjectName("button_float")
        self.horizontalLayout_6.addWidget(self.button_float)
        self.verticalLayout_6.addWidget(self.widget_data)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.layout_save = QtGui.QHBoxLayout()
        self.layout_save.setSpacing(0)
        self.layout_save.setContentsMargins(15, 0, 15, 10)
        self.layout_save.setObjectName("layout_save")
        self.button_save_locally = QtGui.QPushButton(self.centralWidget)
        self.button_save_locally.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.button_save_locally.setFont(font)
        self.button_save_locally.setFlat(True)
        self.button_save_locally.setObjectName("button_save_locally")
        self.layout_save.addWidget(self.button_save_locally)
        self.button_save_directly = QtGui.QPushButton(self.centralWidget)
        self.button_save_directly.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.button_save_directly.setFont(font)
        self.button_save_directly.setFlat(True)
        self.button_save_directly.setObjectName("button_save_directly")
        self.layout_save.addWidget(self.button_save_directly)
        self.verticalLayout_8.addLayout(self.layout_save)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.setStretch(0, 1)
        self.layout_main.addLayout(self.horizontalLayout_7)
        self.line_arguments = QtGui.QLineEdit(self.centralWidget)
        self.line_arguments.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.line_arguments.setFont(font)
        self.line_arguments.setFrame(False)
        self.line_arguments.setAlignment(QtCore.Qt.AlignCenter)
        self.line_arguments.setObjectName("line_arguments")
        self.layout_main.addWidget(self.line_arguments)
        self.progress_bar = QtGui.QProgressBar(self.centralWidget)
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 4))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.progress_bar.setFont(font)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.layout_main.addWidget(self.progress_bar)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_add = QtGui.QPushButton(self.centralWidget)
        self.button_add.setMinimumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_add.setFont(font)
        self.button_add.setFlat(True)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout_2.addWidget(self.button_add)
        self.button_remove = QtGui.QPushButton(self.centralWidget)
        self.button_remove.setMinimumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_remove.setFont(font)
        self.button_remove.setFlat(True)
        self.button_remove.setObjectName("button_remove")
        self.horizontalLayout_2.addWidget(self.button_remove)
        self.button_clear = QtGui.QPushButton(self.centralWidget)
        self.button_clear.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_clear.setFont(font)
        self.button_clear.setFlat(True)
        self.button_clear.setObjectName("button_clear")
        self.horizontalLayout_2.addWidget(self.button_clear)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_2.addLayout(self.horizontalLayout_12)
        self.button_defaults = QtGui.QPushButton(self.centralWidget)
        self.button_defaults.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_defaults.setFont(font)
        self.button_defaults.setFlat(True)
        self.button_defaults.setObjectName("button_defaults")
        self.horizontalLayout_2.addWidget(self.button_defaults)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.button_load = QtGui.QPushButton(self.centralWidget)
        self.button_load.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.button_load.setFont(font)
        self.button_load.setStyleSheet("")
        self.button_load.setFlat(True)
        self.button_load.setObjectName("button_load")
        self.horizontalLayout_2.addWidget(self.button_load)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(25, 10, 0, 10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_directory_2 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.label_directory_2.setFont(font)
        self.label_directory_2.setObjectName("label_directory_2")
        self.horizontalLayout_9.addWidget(self.label_directory_2)
        self.label_directory = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_directory.setFont(font)
        self.label_directory.setObjectName("label_directory")
        self.horizontalLayout_9.addWidget(self.label_directory)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.button_run = QtGui.QPushButton(self.centralWidget)
        self.button_run.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.button_run.setFont(font)
        self.button_run.setObjectName("button_run")
        self.horizontalLayout_3.addWidget(self.button_run)
        self.layout_main.addLayout(self.horizontalLayout_3)
        self.layout_main.setStretch(1, 1)
        toTex.setCentralWidget(self.centralWidget)

        self.retranslateUi(toTex)
        QtCore.QMetaObject.connectSlotsByName(toTex)

    def retranslateUi(self, toTex):
        toTex.setWindowTitle(QtGui.QApplication.translate("toTex", "TEX converter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("toTex", "RUN IF SOURCE OLDER ONLY", None, QtGui.QApplication.UnicodeUTF8))
        self.button_none.setText(QtGui.QApplication.translate("toTex", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.button_up.setText(QtGui.QApplication.translate("toTex", "up ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_up_.setText(QtGui.QApplication.translate("toTex", "up-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_down.setText(QtGui.QApplication.translate("toTex", "down ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_down_.setText(QtGui.QApplication.translate("toTex", "down-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_round.setText(QtGui.QApplication.translate("toTex", "round ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_round_.setText(QtGui.QApplication.translate("toTex", "round-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_black.setText(QtGui.QApplication.translate("toTex", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.button_clamp.setText(QtGui.QApplication.translate("toTex", "clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.button_periodic.setText(QtGui.QApplication.translate("toTex", "periodic", None, QtGui.QApplication.UnicodeUTF8))
        self.button_single.setText(QtGui.QApplication.translate("toTex", "single", None, QtGui.QApplication.UnicodeUTF8))
        self.button_diagonal.setText(QtGui.QApplication.translate("toTex", "diagonal", None, QtGui.QApplication.UnicodeUTF8))
        self.button_all.setText(QtGui.QApplication.translate("toTex", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.button_tiff.setText(QtGui.QApplication.translate("toTex", "tiff", None, QtGui.QApplication.UnicodeUTF8))
        self.button_pixar.setText(QtGui.QApplication.translate("toTex", "pixar", None, QtGui.QApplication.UnicodeUTF8))
        self.button_openexr.setText(QtGui.QApplication.translate("toTex", "openexr", None, QtGui.QApplication.UnicodeUTF8))
        self.button_byte.setText(QtGui.QApplication.translate("toTex", "byte", None, QtGui.QApplication.UnicodeUTF8))
        self.button_short.setText(QtGui.QApplication.translate("toTex", "short", None, QtGui.QApplication.UnicodeUTF8))
        self.button_half.setText(QtGui.QApplication.translate("toTex", "half", None, QtGui.QApplication.UnicodeUTF8))
        self.button_float.setText(QtGui.QApplication.translate("toTex", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.button_save_locally.setText(QtGui.QApplication.translate("toTex", "Save All Locally", None, QtGui.QApplication.UnicodeUTF8))
        self.button_save_directly.setText(QtGui.QApplication.translate("toTex", "Save to Derictory", None, QtGui.QApplication.UnicodeUTF8))
        self.line_arguments.setText(QtGui.QApplication.translate("toTex", "Use it as command line. Write keys only. It overrides all settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.progress_bar.setFormat(QtGui.QApplication.translate("toTex", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add.setText(QtGui.QApplication.translate("toTex", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.button_remove.setText(QtGui.QApplication.translate("toTex", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.button_clear.setText(QtGui.QApplication.translate("toTex", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.button_defaults.setText(QtGui.QApplication.translate("toTex", "Restore Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.button_load.setText(QtGui.QApplication.translate("toTex", "Load txmake.exe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_directory_2.setText(QtGui.QApplication.translate("toTex", "Out Directory:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_directory.setText(QtGui.QApplication.translate("toTex", "All items will be saved next to itselfs", None, QtGui.QApplication.UnicodeUTF8))
        self.button_run.setText(QtGui.QApplication.translate("toTex", "RUN", None, QtGui.QApplication.UnicodeUTF8))

